.gitignore
README.md

Wanting installation instructions added to the README.md instead of searching in the word doc.
Added the installation instructions from the word doc to the README.md in markdown format.
N/A

add installation instructions to readme copied from the word doc

---

odcs-web-client-jetty-standalone/build.gradle
odcsapi-jetty-standalone/build.gradle

Manifest classpath was looking for jars in the root directory.
Prepend the "libs/" directory during the manifest creation.
Tested through the bash script.

fix directory for manifest classspath

---

README.md

Missing documentation in the README.md for the SonarCloud static analysis results.
Add in descriptive blurb along with badges to the README.md
Preview in GitHub and follow links to ensure they are not broken.

add SonarCloud badges to README.md

---

.github/workflows/default.yml
.github/workflows/java_compatibility.yml
README.md
build.gradle

The GitHub action workflow currently focuses on SonarCloud analyze. It is missing dedicated compiling steps and artifact upload.
Add in dedicated compiling steps as well as an upload of artifacts. additionally add in a workflow that tests compiling against JDK 8, 11, and 17
Testing through GitHub Actions on this PR

update github actions workflow to include artifacts

---

.github/dependabot.yml

Dependabot by default creates a PR for every dependency update. This is pretty spammy and not as useful as batching multiple updates together.
Issue #40
Use the Dependabot configuration to batch PR's as long as the updates are minor and patch (definitely could be convinced to batch all updates).
N/A

add PR batching for all minor/patch dependency upgrades

---

.github/dependabot.yml
.github/workflows/default.yml
.github/workflows/java_compatibility.yml
gradle/wrapper/gradle-wrapper.properties

GitHub workflow actions targeted major versions only instead of targeting specific releases. This is a security concern as the latest minor/patch versions could be compromised.
Target specific versions. I did not target hashes as all of the actions are from the GitHub Actions organization. For other owners I think we'd want to target commit hashes.
Added dependabot weekly task for updating the actions.
Will test on this PR.

update github actions to target specific versions

---

.github/workflows/java_compatibility.yml

Missed a pinned github action. Dependabot found it for me.
Update to pinned v4.0.0 for setup-java
Testing in PR

update setup java - missed a version to pin

---

CONTRIBUTING.md
CONTRIBUTORS.md
LICENSE.md

missing contributing/contributors and issue templates
Fixes #24 
Add in contributing/contributors and issue templates copied from opendcs/opendcs with URL links changed to "rest_api"
N/A

add contributing/contributors and issue templates

---

.github/workflows/default.yml
build.gradle
buildSrc/src/main/groovy/opendcs-rest-api.java-conventions.gradle
gradle/libs.versions.toml
odcs-web-client-jetty-standalone/src/test/java/org/opendcs/odcswebclient/jetty/ArgParserTest.java
odcsapi-jetty-standalone/src/test/java/org/opendcs/odcsapi/jetty/ApiCmdLineArgsTest.java
rest_api/src/test/java/org/opendcs/odcsapi/util/ApiHttpUtilTest.java
web_client/build.gradle
web_client/src/test/java/portal/AlgorithmsTest.java

No unit tests exit. Need to demonstrate unit test reports running through CI/CD process using GitHub Actions.
Write some basic unit tests. One for each gradle subproject.
Fixes #30 and #34 
Changes were tests

add basic unit tests to to ensure github actions bundle in CI/CD

---

build.gradle
web_client/build.gradle

SonarQube plugin was not scanning javascript classes.
Update the sources directory to include both java and webapp directories.
Testing in this PR.

scan web client webapp directory in the sonarqube plugin

---

.github/workflows/default.yml
.github/workflows/java_compatibility.yml
.github/workflows/publish.yml

this will include the ability to download an SBOM as well as performs the caching (which we were doing separately already)
The GitHub Dependency Graph is automatically populated in a gradle environment.
Fixes #41 
Add the GitHub action for gradle with the settings for upload the dependency graph.
Tested in the main branch of my fork

use the github gradle build action in order to get the dependency graph to work

---

build.gradle

SonarCloud doesn't know what the last version of the software is. It cannot determine what the "New Code" period is with it
Always set the current version to the last tag but with "+" at the end.
Testing post-merge

set the current version to after the last git tag

---

README.md

Missing repository description for the GitHub Codespaces dev container
Add description to the README.md
N/A

add description to README.md for GitHub codespaces

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiAlgorithmDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiAppDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiComputationDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiConfigDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiDaiBase.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiDaoBase.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiDataSourceDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiDataTypeDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiNetlistDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiPlatformDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiPresentationDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiRefListDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiRoutingDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiSiteDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiTsDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/ApiUnitDAO.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/hydrojson/DbInterface.java

For simplification, getKey and resetKey pass the table/sequence name as a parameter and builds the sequence query based on that variable. We might want to verify that the sequence actually exists to prevent a possible sql injection.
NOTE - Currently, the only use of this is to not ever pass user input into this function. This might be a better solution, as getting all of the sequence names is inefficient.
Fixes #108. 
If user input is passed into this function, it could be problematic for sql injection.
Possible solutions:
1)  Check that the sequence name exists before running the query.  (This is the solution I implemented, but I think it's too inefficient).
2) Make sure user input is never passed into this function. (preferred method)
3) Create new functions for each sequence.
I ran the …

Dynamically created sql using sequence name as a variable.

---

opendcs-rest-api-jetty/src/main/java/org/opendcs/odcsapi/jetty/Start.java
opendcs-rest-api/build.gradle
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/errorhandling/WebAppException.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/lrgsclient/ApiLddsClient.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/lrgsclient/DdsProtocolError.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/opendcs_dep/CompRunner.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/opendcs_dep/TsdbManager.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AppResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/LrgsResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java
opendcs-web-client/build.gradle
opendcs-web-client/src/main/java/api/Gateway.java

There are several calls to throwable.printStackTrace throughout the rest-api project.  These have been flagged as insecure and need to be removed.
Fixes #96. 
Throwable.printStackTrace(...) prints a Throwable and its stack trace to System.Err (by default) which is not easily parseable and can expose sensitive information.
Use a logger to get the same message to the user.
Forced one of these conditions and verified the logger logged the message.

Remove insecure printStackTrace calls.

---

opendcs-web-client/src/main/webapp/resources/js/platforms.js

There are several minor bugs and enhancements needing to be addresses in the web UI, they are:
Bugs
- Schedule Entry page does not highlight in the sidebar when open.
- Fixed propspecs code where prop specs were not being displated if there was no platform sensor data available (on the platforms page)
- Fixed bug where platform selections were not appearing properly.
Minor Enhancements
- New rows added to properties table show up as green.
- action dropdowns appear to the left of the menu instead of below.
- action dropdowns will auto scroll into view where applicable (when they open and are off the visible div).
- login button is now properly margin'd below.

Minor Web UI Bugfixes

---

opendcs-web-client/src/main/webapp/resources/css/main.css
opendcs-web-client/src/main/webapp/resources/js/datatables/datatables.js

Right now, data tables cannot have cell borders.  We need to have the ability to add in cell borders.
Give the ability, from an OOP perspective, for datatables to have cell borders.  This will be an optional object that will be passed into the OpenDcsDataTable constructor, where by default the cell borders will be set to true if this optional object is not passed in.
Verified the cell borders exist if:
1) The object is passed in with cellBorders = true.
2) The object is not passed in.
Verified the cell borders do not exist if:
1) The object is passed in with cellBorders = false;

Give the OpenDcsDataTable class the ability to add cell borders.

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/errorhandling/DatabaseItemNotFoundException.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/errorhandling/MissingParameterException.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PresentationResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/PresentationResourcesTest.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/PresentationResourcesIT.java
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/presentation_get_refs_expected.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/presentation_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/presentation_insert_parent_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/presentation_post_delete_insert_data.json

Fixes #229. 
Fixes #241. 
Replaces DAO usage with OpenDCS DAI implementations.
Unit tests included.

PresentationResources Controller Refactor with Integration Testing for OpenTSDB

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/errorhandling/DatabaseItemNotFoundException.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/errorhandling/MissingParameterException.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ReflistResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/ReflistResourcesTest.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/ReflistResourcesIT.java
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/reflist_get_refs_expected.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/reflist_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/reflist_post_delete_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/reflist_season_from_abbr_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/reflist_season_insert_data.json

Fixes #230.
Fixes #242.  
Replaces DAO usage with OpenDCS DAI implementations. 
Unit tests included.

ReflistResources Controller Refactor with Integration Testing for OpenTSDB

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/NetlistResourcesTest.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/BaseIT.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/NetlistResourcesIT.java
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_cnvtanl_expected.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_cnvtanl_input_data.txt
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_get_expected.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_platform_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_post_delete_insert_data.json
opendcs-rest-api/src/test/resources/org/opendcs/odcsapi/res/it/OPEN_TSDB/netlist_site_insert_data.json

Fixes #238. 
Adds integration testing coverage to refactored NetlistResources.
Integration testing included.

NetlistResources Controller Refactor with Integration Testing for OpenTSDB

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java

There was an unnecessary null check in the NetlistResources Controller for some of the endpoints.
Moved the DatabaseIO creation out of the try-catch blocks and removed the null checks.
Integration tested against OpenTSDB instance.

Fix DatabaseIO Calls in NetlistResources Controller

---

opendcs-rest-api/src/test/java/org/opendcs/odcsapi/fixtures/DatabaseSetupExtension.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/BaseIT.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/it/PlatformResourcesIT.java

The integration testing for PlatformResources relies on storing data via methods added to the OpenDCS Configuration class. These methods should not be in that class, so a refactor is needed.
Swaps usage of methods in the Configuration class for DAO calls via the DAO access methods in the Configuration class.
Integration tested in the REST API against an OpenTSDB instance.

Remove configuration usage for PlatformResources integration testing

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/dao/OpenDcsDatabaseFactory.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PresentationResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/fixtures/DatabaseSetupExtension.java

The mapping of the presentation group parent data created an object even when the parent value was empty.
There is also a key generation error when running against a CWMS database.
Refactored mapping to only create object when presentation group parent data is present. Added key sequencer property.
Integration tested against OpenTSDB and CWMS database instances.

PresentationResources mapping bugfix

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ConfigResources.java

The return type of the readConfig method used in the ConfigResources controller class is being changed to void in this PR: https://github.com/opendcs/opendcs/pull/901
Removed the assignment of the return value of the method.
Integration tested in REST API against OpenTSDB and CWMS database instances.

Fixed void method usage in ConfigResources

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DataSourceResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/DataSourceResourcesTest.java

Custom properties mapping was created when an OpenDCS Toolkit implementation was available.
Removed custom mapping, replaced with Toolkit implementation usage.
Tested via unit tests.

Removed custom properties mapping in DataSourceResources, used Toolkit implementations

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AlgorithmResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AppResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ComputationResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DataSourceResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/OdcsapiResource.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ReflistResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/RoutingResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/SiteResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/TimeSeriesResources.java

Some legacy usages of `WebAppException` were still present instead of the more accurate inheritor classes. Some endpoints were also missing the appropriate checks for missing input parameters.
Replaces generic `WebAppException` usages with appropriate `DatabaseItemNotFoundException` and `MissingParameterExeption`.
Also adds `MissingParameterException` to some endpoints that were missing them.
Integration tested locally against OpenTSDB and CWMS database instances.

Bugfix: Endpoint Response Messages and Thrown Exceptions

---

.github/workflows/build.yml
.github/workflows/sonar.yml

Running sonar analysis from a forked repository with a user who does not have write permissions fails authentication to the SonarCloud service.
Add a github action hook that triggers as the GitHub account to run based on successful build+test execution so that the correct repo permissions are used.
Will be testing by getting @zack-rma to PR into this change.

fix sonar usage so that it can be run from forked repositories

---

opendcs-integration-test/build.gradle

Fixes issue where integration test coverage is reporting as 0%
Point to the correct file
Testing via this PR

fix test coverage report pointing to wrong file

---

opendcs-integration-test/build.gradle
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/opendcs_dep/PropSpecHelper.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/OdcsapiResource.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/opendcs_dep/PropSpecHelperTest.java

Fixes #389 . 
Update reflection mechanism to use new constructors.
Unit tests and by running the webapp in embedded tomcat to check the revised Swagger page.

update PropSpecHelper to use new constructor from toolkit refactors

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/OpenDcsResource.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/RestServices.java

The Swagger try-it-out feature does not work if the REST API context is not the root.
Add the API context to the swagger servers list.
Tested running the embedded Tomcat app.

fix swagger page to use the current API context

---

doc-source/Swagger-README.md
opendcs-web-client/src/main/webapp/resources/jsp/footers/decodes.jsp

Fixes #403 . 
Swagger link goes to /portal/null instead of swagger page
Route to <rest-api-context>/swaggerui/index.html
Test via gradle run task.

fix swagger link in the gui footer

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PlatformResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/PlatformResourcesTest.java

platform sensors need to reference their platform
Storing a new platform sensor throws a null pointer.
Make sure the platform sensors reference their platform.
Unit tests.

fix null pointer when storing platform sensors

---

gradle/libs.versions.toml
opendcs-integration-test/build.gradle
opendcs-integration-test/src/test/java/org/opendcs/odcsapi/res/it/AlgorithmResourcesIT.java
opendcs-integration-test/src/test/java/org/opendcs/odcsapi/sec/AuthorizationTestIT.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AlgorithmResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AppResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ComputationResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ConfigResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DataSourceResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/OdcsapiResource.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PlatformResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PresentationResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ReflistResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/RoutingResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/SiteResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/TimeSeriesResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/sec/SessionResource.java

add integration test that reads all endpoints from the OpenAPI and tests that they all throw 401 unauthorized error codes when the client is not authorized
Almost (if not all) GET endpoints are public, which can potentially leak sensitive information via properties.
Fixes #189. 
Add required authorization to all endpoints except /credentials (this is the login) and /logout
Created an integration test that scrapes the OpenAPI (which is auto generated by finding all registered endpoints) and makes a request against them for all available methods (GET/POST/DELETE/etc) and asserts that an unsessioned client will get an error code 401 response.

add auth to all calls except login/logout

---

opendcs-integration-test/src/test/resources/org/opendcs/odcsapi/res/it/CWMS/config_get_expected.json
opendcs-integration-test/src/test/resources/org/opendcs/odcsapi/res/it/DEFAULT/config_get_expected.json
opendcs-integration-test/src/test/resources/org/opendcs/odcsapi/res/it/DEFAULT/config_input_data.json
opendcs-integration-test/src/test/resources/org/opendcs/odcsapi/res/it/DEFAULT/routing_insert_data.json
opendcs-integration-test/src/test/resources/org/opendcs/odcsapi/res/it/DEFAULT/routing_post_delete_expected.json
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/beans/ApiTransportMedium.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/beans/ApiTsGroup.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/beans/ApiUnit.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/beans/ApiUnitConverter.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ConfigResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PlatformResources.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/RoutingResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/ConfigResourcesTest.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/PlatformResourcesTest.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/RoutingResourcesTest.java

Fixes missing/incorrect mapping of RoutingSpec properties.
Updated both unit and integration tests with proper routing property mapping.
Unit tested and integration tested against OpenTSDB.

Routing Spec Property Mapping Fix

---

opendcs-integration-test/src/test/java/org/opendcs/odcsapi/res/it/ReflistResourcesIT.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ReflistResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/ReflistResourcesTest.java

Fixes #413 .
Fixes #414  . 
fullName appends the enum name to the description, we only want the description
Unit tests and integration tests

update season enums to use description for name not fullName

---

opendcs-integration-test/src/test/java/org/opendcs/odcsapi/res/it/DatatypeUnitResourcesIT.java
opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java

update integration test to include rename
Can't add new engineering units.
Fixes #419 . 
Add null pointer fix and update integration test.
Integration testing.

fix null pointer when creating units

---

opendcs-web-client/src/main/webapp/resources/js/eu_conversions.js

fixes deleting EU conversion delete
Cannot delete unit conversion.
Fixes #417 . 
Fix ajax query missing `?` separator
Tested manually through the user interface.

fix query param separator in ajax request

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/PlatformResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/PlatformResourcesTest.java

Fixes #439 . 
Add null checks
Unit test and through the web gui

fix primitive unboxing in transport medium types

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/ConfigResources.java
opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/ConfigResourcesTest.java

Fixes #420 . 
read data type list to ensure we don't update existing and use the proper DbKey
Unit tested and tested manually through web gui.

read data type list to ensure we don't update existing

---

opendcs-rest-api/build.gradle

Fixes #398 . 
update to go under /build under generated sources
Tested by running `./gradlew build` and checking the git status. Tested running the web gui that the swagger page still loads.

fix swaggerui resources incorrectly going in source directory

---

opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java

Fixes #418 . 
force the db key to be null when editing eu conversion
Tested through web gui.

force the db key to be null when editing eu conversion
